// Renders AI-generated news on news.html and the homepage section.
// Source: data/news.json (regenerated by GitHub Actions every 4 hours).

(function () {
  'use strict';

  const NEWS_URL = 'data/news.json';
  const CACHE_KEY = 'cdit_news_v1';
  const CACHE_TTL_MS = 10 * 60 * 1000; // 10 min

  function escapeHTML(s) {
    return String(s).replace(/[&<>"']/g, c => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    }[c]));
  }

  function shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }

  function timeAgo(iso) {
    const diffMs = Date.now() - new Date(iso).getTime();
    if (Number.isNaN(diffMs) || diffMs < 0) return '';
    const min = Math.floor(diffMs / 60000);
    if (min < 1) return 'الآن';
    if (min < 60) return 'منذ ' + min + ' دقيقة';
    const hours = Math.floor(min / 60);
    if (hours < 24) return 'منذ ' + hours + ' ساعة';
    const days = Math.floor(hours / 24);
    return 'منذ ' + days + ' يوم';
  }

  async function loadNews() {
    try {
      const cached = JSON.parse(localStorage.getItem(CACHE_KEY) || 'null');
      if (cached && Date.now() - cached.cached_at < CACHE_TTL_MS && cached.data) {
        return cached.data;
      }
    } catch {}

    const res = await fetch(NEWS_URL, { cache: 'no-cache' });
    if (!res.ok) throw new Error('news.json fetch failed: ' + res.status);
    const data = await res.json();
    if (!data || !Array.isArray(data.items)) throw new Error('Bad news.json shape');

    try {
      localStorage.setItem(CACHE_KEY, JSON.stringify({ cached_at: Date.now(), data }));
    } catch {}
    return data;
  }

  function cardHTML(item) {
    return ''
      + '<article class="news-card">'
      +   '<div class="news-card-top">'
      +     '<span class="news-emoji">' + escapeHTML(item.emoji || '📰') + '</span>'
      +     '<span class="news-tag">' + escapeHTML(item.tag || 'تقنية') + '</span>'
      +   '</div>'
      +   '<h3 class="news-title">' + escapeHTML(item.title_ar) + '</h3>'
      +   '<p class="news-summary">' + escapeHTML(item.summary_ar) + '</p>'
      +   '<div class="news-card-footer">'
      +     '<span class="news-domain">' + escapeHTML(item.source || '') + '</span>'
      +     '<a href="' + escapeHTML(item.url) + '" target="_blank" rel="noopener" class="news-source-link">'
      +       'اقرأ الأصل ↗'
      +     '</a>'
      +   '</div>'
      + '</article>';
  }

  function renderUpdated(generatedAt) {
    const el = document.getElementById('news-updated');
    if (!el || !generatedAt) return;
    const ago = timeAgo(generatedAt);
    el.textContent = ago ? 'آخر تحديث: ' + ago : '';
  }

  function renderError(loadingEl, errorEl) {
    if (loadingEl) loadingEl.hidden = true;
    if (errorEl) errorEl.hidden = false;
  }

  async function initNewsPage() {
    const grid = document.getElementById('news-grid');
    const loading = document.getElementById('news-loading');
    const errorEl = document.getElementById('news-error');
    if (!grid) return;

    try {
      const data = await loadNews();
      const picked = shuffle(data.items).slice(0, 12);
      grid.innerHTML = picked.map(cardHTML).join('');
      if (loading) loading.hidden = true;
      grid.hidden = false;
      renderUpdated(data.generated_at);
    } catch (e) {
      console.error('News page load failed:', e);
      renderError(loading, errorEl);
    }

    const retry = document.getElementById('news-retry');
    if (retry) retry.addEventListener('click', () => location.reload());
  }

  async function initHomepageNews() {
    const grid = document.getElementById('home-news-grid');
    if (!grid) return;

    try {
      const data = await loadNews();
      const picked = shuffle(data.items).slice(0, 3);
      grid.innerHTML = picked.map(cardHTML).join('');
    } catch (e) {
      console.warn('Homepage news load failed:', e);
      // Hide the entire section if it can't load — never show a broken block
      const section = grid.closest('.home-news-section');
      if (section) section.style.display = 'none';
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
      initNewsPage();
      initHomepageNews();
    });
  } else {
    initNewsPage();
    initHomepageNews();
  }
})();
